"""initial schema

Revision ID: ba637d7a73d7
Revises: 
Create Date: 2026-02-07 19:18:12.601302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba637d7a73d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('cuisine_type', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address_zip', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('default_tax_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('restaurants', 'default_tax_rate')
    op.drop_column('restaurants', 'address_country')
    op.drop_column('restaurants', 'address_zip')
    op.drop_column('restaurants', 'address_state')
    op.drop_column('restaurants', 'address_city')
    op.drop_column('restaurants', 'address_street')
    op.drop_column('restaurants', 'cuisine_type')
    # ### end Alembic commands ###
